import turtle
import time

__Pen = turtle.Pen()


#Get start with Python
screen = turtle.Screen()
screen.setup(width=600, height=600)
screen.bgpic("map.png")
__Pen.shape('turtle')
__Pen.color('yellow')
__Pen.penup()
__Pen.goto(150, (-150))
__Pen.write('new orders!', font = ('Arial', 12, 'bold'))
time.sleep(2)
__Pen.clear()
__Pen.write('START!', font = ('Arial', 12, 'bold'))
time.sleep(2)
__Pen.clear()
__Pen.speed(1)
__Pen.setheading(90)
__Pen.goto(145, 30)
__Pen.setheading(180)
__Pen.goto((-220), 100)
__Pen.setheading(80)
__Pen.write('PERMISI PAKEETT!!!!', font = ('Arial', 12, 'bold'))
time.sleep(2)
__Pen.clear()
__Pen.write('Terima Kasih', font = ('Arial', 12, 'bold'))
time.sleep(1)
__Pen.clear()
__Pen.setheading(0)
__Pen.goto(145, 40)
__Pen.setheading(80)
__Pen.goto(145, 250)
__Pen.setheading(0)
__Pen.write('PAKEET!', font = ('Arial', 12, 'bold'))
time.sleep(2)
__Pen.clear()
__Pen.write('Mari, Bu', font = ('Arial', 12, 'bold'))
time.sleep(1)
__Pen.clear()
__Pen.setheading(270)
__Pen.goto(120, (-200))
__Pen.setheading(180)
__Pen.goto(0, (-170))
__Pen.setheading(80)
__Pen.write('PERMISI PAKEETT!!!!', font = ('Arial', 12, 'bold'))
time.sleep(2)
__Pen.clear()
__Pen.write('Makasih tip nya', font = ('Arial', 12, 'bold'))
time.sleep(1)
__Pen.clear()
__Pen.setheading(270)
__Pen.goto(0, (-200))
__Pen.setheading(0)
__Pen.goto(120, (-200))
__Pen.setheading(90)
__Pen.goto(145, 30)
__Pen.setheading(0)
__Pen.goto(200, 30)
__Pen.setheading(80)
__Pen.goto(220, 70)
__Pen.write('PAKEETT!!!!', font = ('Arial', 12, 'bold'))
time.sleep(2)
__Pen.clear()
__Pen.write('Mari, Kakk', font = ('Arial', 12, 'bold'))
time.sleep(1)
__Pen.clear()
__Pen.write('ORDERS COMPLETED', font = ('Arial', 10, 'bold'))
time.sleep(2)
__Pen.clear()
__Pen.write('Well Done!', font = ('Arial', 12, 'bold'))
time.sleep(1)
__Pen.clear()
turtle.done()
