import turtle
import random

__Pen = turtle.Pen()


#Get start with Python
turtle.bgpic("gradient.gif")
__Pen.speed(1)
__Pen.penup()
__Pen.goto(0, (-200))
__Pen.fillcolor("#333333")
__Pen.pendown()
__Pen.begin_fill()
__Pen.forward(100)
__Pen.left(90)
__Pen.forward(200)
__Pen.right(90)
__Pen.forward(50)
__Pen.left(120)
__Pen.forward(100)
__Pen.left(60)
__Pen.forward(200)
__Pen.left(60)
__Pen.forward(100)
__Pen.left(120)
__Pen.forward(50)
__Pen.right(90)
__Pen.forward(200)
__Pen.left(90)
__Pen.forward(100)
__Pen.end_fill()
__Pen.penup()
__Pen.goto((-90), 0)
__Pen.pencolor("#ffff66")
__Pen.fillcolor("#ffff66")
__Pen.pendown()
for __count in range(2):
    __Pen.begin_fill()
    for __count in range(4):
        __Pen.forward(80)
        __Pen.right(90)
    __Pen.end_fill()
    __Pen.penup()
    __Pen.forward(100)
    __Pen.pendown()
__Pen.pencolor("#000000")
__Pen.pensize(5)

__Pen.penup()
__Pen.goto((-200), (-200))
__Pen.left(90)
__Pen.pendown()
__Pen.forward(300)
__Pen.backward(300)
for __count in range(5):
    __Pen.forward(50)
    __Pen.left(60)
    __Pen.forward(50)
    __Pen.backward(50)
    __Pen.right(90)
    __Pen.forward(50)
    __Pen.backward(50)
    __Pen.left(30)
__Pen.right(90)
for __count in range(4):
    __Pen.penup()
    __Pen.goto(random.randint((-200), 200), random.randint(100, 200))
    __Pen.pendown()
    __Pen.left(90)
    __Pen.circle((-30), 120)
    __Pen.left(120)
    __Pen.circle((-30), 120)
__Pen.penup()
__Pen.goto((-250), 200)
__Pen.pendown()
__Pen.pencolor("#cccccc")
__Pen.fillcolor("#cccccc")
__Pen.begin_fill()
__Pen.circle(50)
__Pen.end_fill()
__Pen.penup()
__Pen.goto((-300), (-200))
__Pen.pendown()
__Pen.left(120)
__Pen.pencolor("#333333")
__Pen.forward(600)
turtle.done()
