import turtle

__Pen = turtle.Pen()


#Get start with Python
turtle.bgcolor("#333333")
__Pen.pencolor("#33ff33")
__Pen.fillcolor("#33ff33")
__Pen.begin_fill()
__Pen.forward(50)
__Pen.right(90)
__Pen.forward(50)
__Pen.right(90)
__Pen.forward(50)
__Pen.right(90)
__Pen.forward(50)
__Pen.right(90)
__Pen.end_fill()
__Pen.penup()
__Pen.right(90)
__Pen.forward(60)
__Pen.left(90)
__Pen.pendown()
__Pen.pencolor("#ffff00")
__Pen.fillcolor("#ffff00")
__Pen.begin_fill()
__Pen.forward(50)
__Pen.right(90)
__Pen.forward(50)
__Pen.right(90)
__Pen.forward(50)
__Pen.right(90)
__Pen.forward(50)
__Pen.right(90)
__Pen.end_fill()
__Pen.penup()
__Pen.backward(60)
__Pen.pendown()
__Pen.pencolor("#33ffff")
__Pen.fillcolor("#33ffff")
__Pen.begin_fill()
__Pen.forward(50)
__Pen.right(90)
__Pen.forward(50)
__Pen.right(90)
__Pen.forward(50)
__Pen.right(90)
__Pen.forward(50)
__Pen.right(90)
__Pen.end_fill()
__Pen.penup()
__Pen.left(90)
__Pen.forward(60)
__Pen.right(90)
__Pen.pendown()
__Pen.pencolor("#ff0000")
__Pen.fillcolor("#ff0000")
__Pen.begin_fill()
__Pen.forward(50)
__Pen.right(90)
__Pen.forward(50)
__Pen.right(90)
__Pen.forward(50)
__Pen.right(90)
__Pen.forward(50)
__Pen.right(90)
__Pen.end_fill()
__Pen.penup()
__Pen.right(90)
__Pen.forward(150)
__Pen.pencolor("#ffffff")
__Pen.write('Microsoft', font = ('Arial', 20, 'normal'))
turtle.done()
