import turtle

__Pen = turtle.Pen()


#Get start with Python
turtle.bgcolor("#FDE2F3")
__Pen.pencolor("#6666cc")
__Pen.fillcolor("#ccccff")
__Pen.penup()
__Pen.goto((-100), 100)
__Pen.pendown()
__Pen.begin_fill()
__Pen.forward(200)
__Pen.right(90)
__Pen.forward(200)
__Pen.right(90)
__Pen.forward(200)
__Pen.right(90)
__Pen.forward(200)
__Pen.right(90)
__Pen.end_fill()
__Pen.penup()
__Pen.pencolor("#999999")
__Pen.fillcolor("#cccccc")
__Pen.left(90)
__Pen.forward(5)
__Pen.right(90)
__Pen.forward(50)
__Pen.pendown()
__Pen.begin_fill()
__Pen.forward(100)
__Pen.left(90)
__Pen.forward(100)
__Pen.left(90)
__Pen.forward(100)
__Pen.left(90)
__Pen.forward(100)
__Pen.left(90)
__Pen.end_fill()
__Pen.left(90)
__Pen.penup()
__Pen.forward(70)
__Pen.right(90)
__Pen.forward(25)
__Pen.pendown()
__Pen.circle(5)
__Pen.penup()
__Pen.forward(50)
__Pen.pendown()
__Pen.circle(5)
__Pen.penup()
__Pen.goto((-105), 100)
__Pen.pendown()
__Pen.begin_fill()
__Pen.right(90)
__Pen.forward(150)
__Pen.right(90)
__Pen.forward(50)
__Pen.right(90)
__Pen.forward(150)
__Pen.right(90)
__Pen.forward(50)
__Pen.end_fill()
__Pen.penup()
__Pen.goto(105, 100)
__Pen.pendown()
__Pen.begin_fill()
__Pen.right(90)
__Pen.forward(150)
__Pen.left(90)
__Pen.forward(50)
__Pen.left(90)
__Pen.forward(150)
__Pen.left(90)
__Pen.forward(50)
__Pen.end_fill()
__Pen.penup()
__Pen.goto((-100), (-105))
__Pen.pendown()
__Pen.begin_fill()
__Pen.left(90)
__Pen.forward(100)
__Pen.left(90)
__Pen.forward(50)
__Pen.left(90)
__Pen.forward(100)
__Pen.left(90)
__Pen.forward(50)
__Pen.end_fill()
__Pen.penup()
__Pen.forward((-150))
__Pen.pendown()
__Pen.begin_fill()
__Pen.left(90)
__Pen.forward(100)
__Pen.left(90)
__Pen.forward(50)
__Pen.left(90)
__Pen.forward(100)
__Pen.left(90)
__Pen.forward(50)
__Pen.end_fill()
turtle.done()
